// vue_todo2/src/client/Home/TodoItem.vue
<template>
  <li class="flex items-center justify-between p-4 border-b">
    <div class="flex items-center">
      <input
        type="checkbox"
        :checked="todo.completed === 1"
        @change="toggleComplete"
        class="mr-2"
      />
      <span :class="{ 'line-through': todo.completed === 1 }">{{ todo.title }}</span>
    </div>
    <div>
      <button
        @click="editTodo"
        class="px-3 py-1 text-blue-500 hover:text-blue-700"
      >
        Edit
      </button>
      <button
        @click="deleteTodo"
        class="px-3 py-1 text-red-500 hover:text-red-700"
      >
        Delete
      </button>
    </div>
  </li>
</template>

<script setup lang="ts">
import { useTodoStore } from './stores/todo';
import type { Todo } from './types';

const props = defineProps<{
  todo: Todo;
}>();

const emit = defineEmits(['edit']);

const todoStore = useTodoStore();

const toggleComplete = async () => {
  await todoStore.updateTodo(props.todo.id, { completed: props.todo.completed ? 0 : 1 });
};

const editTodo = () => {
  emit('edit', props.todo);
};

const deleteTodo = async () => {
  if (confirm('Are you sure you want to delete this TODO?')) {
    await todoStore.deleteTodo(props.todo.id);
  }
};
</script>

// todo2/src/client/Home/TodoItem.tsx
import React, { useState } from 'react';
import { Todo } from './types';
import EditTodoDialog from './EditTodoDialog';
import { deleteTodo } from './api';

type Props = {
  todo: Todo;
  onUpdate: (todo: Todo) => void;
  onDelete: (id: number) => void;
};

const TodoItem: React.FC<Props> = ({ todo, onUpdate, onDelete }) => {
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);

  const handleDelete = async () => {
    await deleteTodo(todo.id);
    onDelete(todo.id);
  };

  return (
    <li className='flex items-center justify-between border-b border-gray-300 py-2'>
      <span className={todo.completed ? 'line-through text-gray-500' : ''}>
        {todo.title}
      </span>
      <div>
        <button
          onClick={() => setIsEditDialogOpen(true)}
          className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 rounded mr-2'
        >
          Edit
        </button>
        <button
          onClick={handleDelete}
          className='bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded'
        >
          Delete
        </button>
      </div>
      {isEditDialogOpen ? (
        <EditTodoDialog
        isOpen={isEditDialogOpen}
        onClose={() => setIsEditDialogOpen(false)}
        todo={todo}
        onUpdate={onUpdate}
        />
      ): 
      null}

    </li>
  );
};

export default TodoItem;
