// vue_todo2/src/client/Home/TodoList.vue
<template>
  <div>
    <ul class="space-y-4">
      <li v-for="todo in todos" :key="todo.id" class="bg-white shadow p-4 rounded-md">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-semibold">{{ todo.title }}</h3>
          <div class="flex space-x-2">
            <button @click="editTodo(todo)" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              <!-- 
              <PencilIcon class="h-5 w-5" />
              -->
              Edit
            </button>
            <button @click="deleteTodoItem(todo.id)" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
              <!--
              <TrashIcon class="h-5 w-5" />
              -->
              Delete
            </button>
          </div>
        </div>
        <p class="mt-2 text-gray-600">{{ todo.content }}</p>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { getTodos, deleteTodo } from './api';
import { Todo } from './types';
//import { PencilIcon, TrashIcon } from '@heroicons/vue/24/outline';

const todos = ref<Todo[]>([]);

const props = defineProps<{
  onEdit: (todo: Todo) => void;
}>();

onMounted(async () => {
  await fetchTodos();
});

const fetchTodos = async () => {
  todos.value = await getTodos();
};

const deleteTodoItem = async (id?: number) => {
  if (!id) return;
  if (confirm('本当に削除しますか？')) {
    await deleteTodo(id);
    await fetchTodos();
  }
};

const editTodo = (todo: Todo) => {
  props.onEdit(todo);
};

defineExpose({
  fetchTodos
});
</script>

// svelte_todo4/src/client/Home/TodoList.svelte
<!-- src/components/TodoList.svelte -->
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { Todo } from './schema';
  import TodoDialog from "./TodoDialog.svelte";
  import { 
    getTodos, createTodo, updateTodo, deleteTodo, searchTodos 
  } from "./api";

  export let todos: Todo[] = [];
  let showForm = false;
  let editingTodo: Partial<Todo> | undefined = undefined;

  const dispatch = createEventDispatcher();

  const handleEdit = (todo: Todo) => {
    editingTodo = todo;
    showForm = true;
    //dispatch('edit', todo);
  };

  const handleDelete = async (id: number) => {
    await deleteTodo(id);
    location.reload();
    //dispatch('delete', id);
  };
</script>

<div class="mt-6">
  {#each todos as todo (todo.id)}
    <div class="bg-white p-4 rounded-lg shadow mb-4 flex justify-between items-center">
      <div>
        <h3 class="text-lg font-bold">{todo.title}</h3>
        <p class="text-gray-600">{todo.content}</p>
      </div>
      <div>
        <button on:click={() => handleEdit(todo)} class="px-3 py-1 rounded bg-blue-500 text-white hover:bg-blue-600 mr-2">
          Edit
        </button>
        <button on:click={() => handleDelete(todo.id)} class="px-3 py-1 rounded bg-red-500 text-white hover:bg-red-600">
          Delete
        </button>
      </div>
    </div>
  {:else}
    <p class="text-gray-600">No todos found.</p>
  {/each}

  {#if showForm}
  <TodoDialog
    bind:isOpen={showForm}
    todo={editingTodo}
    on:submit={null}
  />
  {/if}
</div>
