// todo4/src/client/Home/TodoList.tsx
import React, { useState, useEffect } from 'react';
import { getTodos, deleteTodo } from './api';
import TodoDialog from './TodoDialog';
import { Todo } from './utils';
//import { PencilIcon, TrashIcon } from '@heroicons/react/outline';

const TodoList: React.FC = () => {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [selectedTodo, setSelectedTodo] = useState<Todo | null>(null);
  const [isDialogOpen, setIsDialogOpen] = useState(false);

  const refreshTodos = async () => {
    const fetchedTodos = await getTodos();
    setTodos(fetchedTodos);
  };

  useEffect(() => {
    refreshTodos();
  }, []);

  const handleEdit = (todo: Todo) => {
    setSelectedTodo(todo);
    setIsDialogOpen(true);
  };

  const handleDelete = async (id: number) => {
    if (window.confirm('本当に削除しますか?')) {
      await deleteTodo(id);
      await refreshTodos();
    }
  };

  const handleCloseDialog = () => {
    setIsDialogOpen(false);
    setSelectedTodo(null);
  };

  return (
    <div>
      <button
        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4"
        onClick={() => setIsDialogOpen(true)}
      >
        TODOを追加
      </button>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {todos.map((todo) => (
          <div key={todo.id} className="bg-white rounded-lg shadow-md p-4">
            <h2 className="text-lg font-bold mb-2">{todo.title}</h2>
            <p className="text-gray-700 mb-4">{todo.content}</p>
            <div className="flex justify-end">
              <button
                className="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded mr-2"
                onClick={() => handleEdit(todo)}
              >
                {/*
                <PencilIcon className="h-5 w-5" />
                */}
                Ediit
              </button>
              <button
                className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
                onClick={() => handleDelete(todo.id)}
              >
                Delete 
                {/*
                <TrashIcon className="h-5 w-5" />
                */}
              </button>
            </div>
          </div>
        ))}
      </div>

      {isDialogOpen ? (
        <TodoDialog
        isOpen={isDialogOpen}
        onClose={handleCloseDialog}
        todo={selectedTodo}
        refreshTodos={refreshTodos}
      />
      ): null}
    </div>
  );
};

export default TodoList;

// vue_todo2/src/client/Home/TodoList.vue
<template>
  <div>
    <ul class="space-y-4">
      <li v-for="todo in todos" :key="todo.id" class="bg-white shadow p-4 rounded-md">
        <div class="flex items-center justify-between">
          <h3 class="text-lg font-semibold">{{ todo.title }}</h3>
          <div class="flex space-x-2">
            <button @click="editTodo(todo)" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
              <!-- 
              <PencilIcon class="h-5 w-5" />
              -->
              Edit
            </button>
            <button @click="deleteTodoItem(todo.id)" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
              <!--
              <TrashIcon class="h-5 w-5" />
              -->
              Delete
            </button>
          </div>
        </div>
        <p class="mt-2 text-gray-600">{{ todo.content }}</p>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { getTodos, deleteTodo } from './api';
import { Todo } from './types';
//import { PencilIcon, TrashIcon } from '@heroicons/vue/24/outline';

const todos = ref<Todo[]>([]);

const props = defineProps<{
  onEdit: (todo: Todo) => void;
}>();

onMounted(async () => {
  await fetchTodos();
});

const fetchTodos = async () => {
  todos.value = await getTodos();
};

const deleteTodoItem = async (id?: number) => {
  if (!id) return;
  if (confirm('本当に削除しますか？')) {
    await deleteTodo(id);
    await fetchTodos();
  }
};

const editTodo = (todo: Todo) => {
  props.onEdit(todo);
};

defineExpose({
  fetchTodos
});
</script>
