// todo2/src/client/Home/TodoList.tsx
import React, { useState, useEffect } from "react";
import axios from "axios";
import TodoDialog from "./TodoDialog";
import { z } from "zod";
const API_URL = "/api/todos";

// Zod バリデーションスキーマ
const todoSchema = z.object({
  title: z.string().min(1, { message: "タイトルは必須です" }),
  content: z.string().min(1, { message: "内容は必須です" }),
  publicType: z.enum(["public", "private"]),
  foodOrange: z.boolean().optional(),
  foodApple: z.boolean().optional(),
  foodBanana: z.boolean().optional(),
  pubDate1: z.string().optional(),
  pubDate2: z.string().optional(),
  pubDate3: z.string().optional(),
  qty1: z.string().optional(),
  qty2: z.string().optional(),
  qty3: z.string().optional(),
});

const TodoList = () => {
  const [todos, setTodos] = useState([]);
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [currentTodo, setCurrentTodo] = useState(null);
  const [deleteConfirmation, setDeleteConfirmation] = useState(null);

  useEffect(() => {
    fetchTodos();
  }, []);

  const fetchTodos = async () => {
    try {
      const response = await axios.get(API_URL);
      setTodos(response.data);
    } catch (error) {
      console.error("Error fetching todos:", error);
    }
  };

  const handleAddTodo = () => {
    setCurrentTodo(null);
    setIsDialogOpen(true);
  };

  const handleEditTodo = (todo) => {
    setCurrentTodo(todo);
    setIsEditDialogOpen(true);
  };

  const handleDeleteTodo = (todo) => {
    setDeleteConfirmation(todo);
  };

  const confirmDeleteTodo = async () => {
    try {
      await axios.delete(`${API_URL}/${deleteConfirmation.id}`);
      setTodos(todos.filter((todo) => todo.id !== deleteConfirmation.id));
      setDeleteConfirmation(null);
    } catch (error) {
      console.error("Error deleting todo:", error);
    }
  };

  const handleCloseDialog = () => {
    setIsDialogOpen(false);
    setIsEditDialogOpen(false);
    setCurrentTodo(null);
  };

  const handleSaveTodo = async (todoData) => {
    try {
      // バリデーション
      todoSchema.parse(todoData);

      if (currentTodo) {
        // Update existing todo
        const response = await axios.put(
          `${API_URL}/${currentTodo.id}`,
          todoData
        );
        setTodos(
          todos.map((todo) =>
            todo.id === currentTodo.id ? response.data : todo
          )
        );
      } else {
        // Create new todo
        const response = await axios.post(API_URL, todoData);
        setTodos([...todos, response.data]);
      }
      handleCloseDialog();
    } catch (error) {
      if (error instanceof z.ZodError) {
        // Zod バリデーションエラー
        const errorMessages = error.errors.map((err) => err.message).join(", ");
        alert(`バリデーションエラー: ${errorMessages}`);
      } else {
        console.error("Error saving todo:", error);
      }
    }
  };

  const handleSearch = async (query) => {
    try {
      const response = await axios.get(`${API_URL}/search?query=${query}`);
      setTodos(response.data);
    } catch (error) {
      console.error("Error searching todos:", error);
    }
  };

  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">TODO List</h1>

      <div className="mb-4">
        <input
          type="text"
          placeholder="Search..."
          className="border border-gray-400 px-3 py-2 rounded-md w-full md:w-1/2"
          onChange={(e) => handleSearch(e.target.value)}
        />
      </div>

      <button
        className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mb-4"
        onClick={handleAddTodo}
      >
        Add Todo
      </button>

      <ul>
        {todos.map((todo) => (
          <li key={todo.id} className="border-b border-gray-300 py-2">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-medium">{todo.title}</h3>
                <p className="text-gray-600">{todo.content}</p>
              </div>
              <div>
                <button
                  className="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-1 px-2 rounded mr-2"
                  onClick={() => handleEditTodo(todo)}
                >
                  Edit
                </button>
                <button
                  className="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded"
                  onClick={() => handleDeleteTodo(todo)}
                >
                  Delete
                </button>
              </div>
            </div>
          </li>
        ))}
      </ul>
      {isDialogOpen ? (
        <TodoDialog
        isOpen={isDialogOpen}
        isEdit={false}
        todo={currentTodo}
        onClose={handleCloseDialog}
        onSave={handleSaveTodo}
        />
      )
      : null}
      {isEditDialogOpen ? (
        <TodoDialog
        isOpen={isEditDialogOpen}
        isEdit={true}
        todo={currentTodo}
        onClose={handleCloseDialog}
        onSave={handleSaveTodo}
        />
      ) : null}

      {/* 削除確認ダイアログ */}
      {deleteConfirmation ? (
      <div
      open={!!deleteConfirmation}
      onClose={() => setDeleteConfirmation(null)}
      className="fixed z-10 inset-0 overflow-y-auto"
      >
        <div className="flex items-center justify-center min-h-screen">
          <div className="fixed inset-0 bg-black opacity-30" />

          <div className="bg-white rounded-lg p-6 max-w-sm z-50">
            <div className="flex items-center mb-4">
              <h3 className="text-lg font-bold">
                Confirm Delete
              </h3>
            </div>
            <p>Are you sure you want to delete this todo?</p>
            <div className="mt-4 flex justify-end">
              <button
                className="bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded mr-2"
                onClick={() => setDeleteConfirmation(null)}
              >
                Cancel
              </button>
              <button
                className="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded"
                onClick={confirmDeleteTodo}
              >
                Delete
              </button>
            </div>
          </div>
        </div>
      </div>
      )
      : null}
      
    </div>
  );
};

export default TodoList;

// vue_todo1/src/client/Todo1_1/TodoList.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { Todo } from './types';
import type { TodoInput } from './schema';
import TodoDialog from './TodoDialog.vue';
import Test from './Test.vue';

const todos = ref<Todo[]>([]);
const searchQuery = ref('');
const dialog = ref({
  isOpen: false,
  mode: 'create' as const,
  todo: undefined as Todo | undefined,
});
//const editTodo = ref(undefined as Todo | undefined);
const edititem = ref(undefined as Todo | undefined);
const testitem = ref({a: 111});

const fetchTodos = async () => {
  try {
    const response = await fetch(`/api/todos${
      searchQuery.value ? `?search=${encodeURIComponent(searchQuery.value)}` : ''
    }`);
    todos.value = await response.json();
  } catch (error) {
    console.error('Failed to fetch todos:', error);
  }
};

const createTodo = async (todoData: TodoInput) => {
  try {
    const response = await fetch('/api/todos', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(todoData),
    });
    if (response.ok) {
      await fetchTodos();
      dialog.value.isOpen = false;
    }
  } catch (error) {
    console.error('Failed to create todo:', error);
  }
};

const updateTodo = async (id: number, todoData: TodoInput) => {
  try {
    const response = await fetch(`/api/todos/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(todoData),
    });
    if (response.ok) {
      await fetchTodos();
      dialog.value.isOpen = false;
    }
  } catch (error) {
    console.error('Failed to update todo:', error);
  }
};

const deleteTodo = async (id: number) => {
  if (!confirm('本当に削除しますか？')) return;
  
  try {
    const response = await fetch(`/api/todos/${id}`, {
      method: 'DELETE',
    });
    if (response.ok) {
      await fetchTodos();
    }
  } catch (error) {
    console.error('Failed to delete todo:', error);
  }
};

const openCreateDialog = () => {
  dialog.value = {
    isOpen: true,
    mode: 'create',
    todo: undefined,
  };
};

const openEditDialog = (todo: Todo) => {
console.log("#openEditDialog");
console.log(todo);
/*
  dialog.value = {
    isOpen: true,
    mode: 'edit',
    todo: todo,
  };
*/
  edititem.value = todo;
};

const handleDialogSave = (todoData: TodoInput) => {
  if (dialog.value.mode === 'edit' && dialog.value.todo) {
    updateTodo(dialog.value.todo.id, todoData);
  } else {
    createTodo(todoData);
  }
};

onMounted(fetchTodos);
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <div class="mb-6 flex justify-between items-center">
      <div class="flex-1 max-w-md">
        <input
          v-model="searchQuery"
          @input="fetchTodos"
          type="text"
          placeholder="TODOを検索..."
          class="w-full px-4 py-2 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"
        />
      </div>
      <button
        @click="openCreateDialog"
        class="ml-4 px-4 py-2 bg-indigo-600 text-white rounded-md hover:bg-indigo-700"
      >
        新規作成
      </button>
    </div>

    <div class="bg-white shadow overflow-hidden rounded-lg">
      <ul class="divide-y divide-gray-200">
        <li v-for="todo in todos" :key="todo.id" class="p-4 hover:bg-gray-50">
          <div class="flex items-center justify-between">
            <div class="flex items-center">
              <input
                type="checkbox"
                :checked="todo.completed"
                @change="updateTodo(todo.id, { ...todo, completed: !todo.completed })"
                class="rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
              />
              <div class="ml-4">
                <h3 class="text-lg font-medium" :class="{ 'line-through': todo.completed }">
                  {{ todo.title }}
                </h3>
                <p v-if="todo.description" class="text-gray-500">{{ todo.description }}</p>
              </div>
            </div>
            <div class="flex space-x-2">
              <button
                @click="openEditDialog(todo)"
                class="px-3 py-1 text-sm text-indigo-600 hover:text-indigo-900"
              >
                編集
              </button>
              <button
                @click="deleteTodo(todo.id)"
                class="px-3 py-1 text-sm text-red-600 hover:text-red-900"
              >
                削除
              </button>
            </div>
          </div>
        </li>
      </ul>
    </div>

    <span>edititem {{ JSON.stringify(edititem) }}</span>
    <!--
    -->
    <Test 
    :mode="dialog.mode"
    :param1="1"
    :edititem = "edititem"
    :testitem = "testitem"
    />

    <TodoDialog
      :is-open="dialog.isOpen"
      :mode="dialog.mode"
      :todo="dialog.todo"
      :edititem = "edititem"
      @close="dialog.isOpen = false"
      @save="handleDialogSave"
    />
  </div>
</template>
