// todo4/src/client/Home/SearchBar.tsx
import React, { useState } from 'react';

const SearchBar = ({ onSearch }) => {
  const [query, setQuery] = useState('');

  const handleInputChange = (e) => {
    setQuery(e.target.value);
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    onSearch(query);
  };

  return (
    <form onSubmit={handleSubmit} className="mb-4">
      <input
        type="text"
        placeholder="TODOを検索"
        value={query}
        onChange={handleInputChange}
        className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
      />
    </form>
  );
};

export default SearchBar;

// vue_todo1/src/client/Home/SearchBar.vue
<template>
  <div class="mb-4">
    <input
      type="text"
      v-model="query"
      placeholder="Search TODOs"
      class="w-full px-3 py-2 border rounded"
      @input="searchTodos"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
//import { useTodoStore } from '@/stores/todo';
import { useTodoStore } from './stores/todo';

const query = ref('');
const todoStore = useTodoStore();

const searchTodos = () => {
  todoStore.searchTodos(query.value);
};
</script>
