// todo1/src/client/Home/TodoDialog.tsx
import React, { useState } from "react";
import { z } from "zod";
import axios from "axios";

const todoSchema = z.object({
  title: z.string().min(1, "Title is required"),
  description: z.string().optional(),
});

const TodoDialog = ({ setTodos, editingTodo, onClose }) => {
  const [formData, setFormData] = useState(
    editingTodo || { title: "", description: "" }
  );
  const [errors, setErrors] = useState({});

  const handleSubmit = async (e) => {
    e.preventDefault();

    // バリデーション
    const result = todoSchema.safeParse(formData);
    if (!result.success) {
      const errorMessages = result.error.format();
      setErrors({
        title: errorMessages.title?._errors[0],
      });
      return;
    }

    try {
      if (editingTodo) {
        // 編集
        const response = await axios.put(
          `/api/todos/${editingTodo.id}`,
          formData
        );
        setTodos((prev) =>
          prev.map((todo) =>
            todo.id === editingTodo.id ? { ...todo, ...response.data } : todo
          )
        );
      } else {
        // 新規追加
        const response = await axios.post("/api/todos", formData);
        setTodos((prev) => [...prev, response.data]);
      }
      onClose();
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
      <div className="bg-white p-6 rounded-md shadow-lg w-96">
        <h2 className="text-xl font-bold mb-4">
          {editingTodo ? "Edit TODO" : "Add TODO"}
        </h2>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium">Title</label>
            <input
              type="text"
              value={formData.title}
              onChange={(e) =>
                setFormData({ ...formData, title: e.target.value })
              }
              className="border p-2 w-full rounded-md"
            />
            {errors.title && (
              <p className="text-red-500 text-sm">{errors.title}</p>
            )}
          </div>
          <div>
            <label className="block text-sm font-medium">Description</label>
            <textarea
              value={formData.description}
              onChange={(e) =>
                setFormData({ ...formData, description: e.target.value })
              }
              className="border p-2 w-full rounded-md"
            ></textarea>
          </div>
          <div className="flex justify-end gap-2">
            <button
              type="button"
              onClick={onClose}
              className="bg-gray-500 text-white px-4 py-2 rounded-md"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="bg-blue-500 text-white px-4 py-2 rounded-md"
            >
              Save
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default TodoDialog;

// vue_todo1/src/client/Home/TodoDialog.vue
<template>
  <div class="fixed inset-0 bg-gray-500 bg-opacity-50 flex justify-center items-center">
    <div class="bg-white p-6 rounded w-96">
      <h2 class="text-xl font-bold mb-4">
        {{ mode === "add" ? "Add TODO" : "Edit TODO" }}
      </h2>
      <form @submit.prevent="validateAndSave">
        <div class="mb-4">
          <label class="block font-bold mb-1">Title</label>
          <input
            v-model="form.title"
            class="border rounded px-4 py-2 w-full"
            type="text"
          />
          <p v-if="errors.title" class="text-red-500 text-sm">
            {{ errors.title }}
          </p>
        </div>
        <div class="mb-4">
          <label class="block font-bold mb-1">Description</label>
          <textarea
            v-model="form.description"
            class="border rounded px-4 py-2 w-full"
          ></textarea>
        </div>
        <div class="flex justify-end">
          <button
            type="button"
            class="bg-gray-500 text-white px-4 py-2 rounded mr-2"
            @click="$emit('close')"
          >
            Cancel
          </button>
          <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">
            Save
          </button>
        </div>
      </form>
    </div>
  </div>
</template>

<script>
import { z } from "zod";

export default {
  props: {
    mode: String,
    currentTodo: Object,
  },
  emits: ["close", "save"],
  data() {
    return {
      form: {
        title: this.currentTodo?.title || "",
        description: this.currentTodo?.description || "",
      },
      errors: {},
    };
  },
  methods: {
    validateAndSave() {
      const schema = z.object({
        title: z.string().nonempty("Title is required."),
      });

      const result = schema.safeParse(this.form);

      if (!result.success) {
        this.errors = result.error.flatten().fieldErrors;
      } else {
        this.errors = {};
        this.$emit("save", this.form);
      }
    },
  },
};
</script>
